#ifndef MICROPYTHON_GTEST_CONFIG_H
#define MICROPYTHON_GTEST_CONFIG_H
#include <port/mpconfigport_common.h>
#define MICROPY_CONFIG_ROM_LEVEL (MICROPY_CONFIG_ROM_LEVEL_BASIC_FEATURES)
#define MICROPY_ENABLE_COMPILER (1)
#define MICROPY_ENABLE_GC (1)
#define MICROPY_PY_GC (1)
#define MICROPY_ENABLE_EXTERNAL_IMPORT (0)
#define MICROPY_LONGINT_IMPL (MICROPY_LONGINT_IMPL_MPZ)
#define MICROPY_FLOAT_IMPL (MICROPY_FLOAT_IMPL_NONE)
#define MICROPY_NLR_SETJMP (1)
#define MICROPY_GCREGS_SETJMP (1)
#define MICROPY_STACK_CHECK (0)
#define MICROPY_PY_SYS_PLATFORM "gtest-embed"
#define MICROPY_PY_IO (0)
#endif
